### ISSUE TITLE
The data file is lost!

### ISSUE THREAD

**Issue by MorchelPeng** [DLR-RM/SingleViewReconstruction#10]
The house.obj and camera position files are then stored in a data folder, however, the link of the data is missing.

**Comment by themasterlink** [comment]
Hey,

I am confused by the statement: `the link of the data is missing.`

Do you mean the link to the SUNCG dataset? 

Best,
Max

**Comment by MorchelPeng** [comment]
> yes，the link https://github.com/DLRRM/SingleViewReconstruction/blob/main/SUNCG/data is not available

**Comment by themasterlink** [comment]
Hey,

are you referring to this README.md: https://github.com/DLR-RM/SingleViewReconstruction/edit/main/SUNCG/README.md

With this sentence: `The house.obj and camera position files are then stored in a data folder, which is automatically generated. With the following structure:`

As it says there the folder is generated by executing the script or you could you explain yourself a bit more in detail.

Best,
Max

**Comment by MorchelPeng** [comment]
I misunderstood the meaning before, thanks, it is ok now
