### ISSUE TITLE
Camera pose

### ISSUE THREAD

**Issue by ghost** [DLR-RM/SingleViewReconstruction#11]
Thank you for your amazing work!

I'm new to the 3d reconstruction work.
I have read your paper and find that the camera pose is extremly important to the reconstruction task.
![image](https://user-images.githubusercontent.com/71435435/189466402-50a24441-5fdd-4d7c-ac05-d49718682ae7.png)
![image](https://user-images.githubusercontent.com/71435435/189466427-5ffadac1-8f1d-467a-912c-3801c2164f57.png)

Could you please tell me that 
how do I get a 3-dimensional reconstruction if I input an image and do not know the corresponding camera pose when the image was taken?

Thank you

**Comment by themasterlink** [comment]
Hey,

in this work we assumed a fixed camera height, with a fixed camera tilt and no inplane rotation, to reduce the solution space. We used the value presented in the SUNCGToolbox.

This is designed to work with robots, which already have a desired height and tilt, of course one can train a method with more range. This will likely reduce the performance.

Best,
Max

**Comment by ghost** [comment]
Thank you for your relpy. I am trying to construct a model which can estimate camera pose.

________________________________
发件人: Maximilian Denninger ***@***.***>
发送时间: 2022年9月10日 13:37
收件人: DLR-RM/SingleViewReconstruction ***@***.***>
抄送: 文翊涵 ***@***.***>; Author ***@***.***>
主题: Re: [DLR-RM/SingleViewReconstruction] Camera pose (Issue #11)


Hey,

in this work we assumed a fixed camera height, with a fixed camera tilt and no inplane rotation, to reduce the solution space. We used the value presented in the SUNCGToolbox.

This is designed to work with robots, which already have a desired height and tilt, of course one can train a method with more range. This will likely reduce the performance.

Best,
Max

―

**Comment by themasterlink** [comment]
Hey,

that is not done in this work.

Best,
Max

**Comment by ghost** [comment]
Hey,

Thank you for your reply! I mean I will try to construct a model by myself to finish my project.😄
Hope I can get some progress

Best regards,
yihan
