### ISSUE TITLE
Environment installation failure

### ISSUE THREAD

**Issue by lindenmp** [DLR-RM/SingleViewReconstruction#5]
Hi,

I'm having trouble installing the environment using the .yml file. Whenever I run `conda env create -f environment.yml` I get the following error:

> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound: 
>   - cudatoolkit==10.0.130=0
>   - mkl-service==2.3.0=py37he904b0f_0
>   - numpy-base==1.18.5=py37hde5b4d6_0
>   - tensorflow==1.15.0=gpu_py37h0f0df58_0
>   - readline==8.0=h7b6447c_0
>   - ncurses==6.2=he6710b0_1
>   - python==3.7.7=hcff3b4d_5
>   - sqlite==3.32.3=h62c20be_0
>   - libstdcxx-ng==9.1.0=hdf63c60_0
>   - libprotobuf==3.12.3=hd408876_0
>   - tensorflow-gpu==1.15.0=h0d30ee6_0
>   - libedit==3.1.20191231=h7b6447c_0
>   - mkl==2020.1=217
>   - _tflow_select==2.1.0=gpu
>   - ld_impl_linux-64==2.33.1=h53a641e_7
>   - mkl_fft==1.1.0=py37h23d657b_0
>   - wrapt==1.12.1=py37h7b6447c_1
>   - tensorflow-base==1.15.0=gpu_py37h9dcbed7_0
>   - zlib==1.2.11=h7b6447c_3
>   - cupti==10.0.130=0
>   - intel-openmp==2020.1=217
>   - xz==5.2.5=h7b6447c_0
>   - numpy==1.18.5=py37ha1c710e_0
>   - c-ares==1.15.0=h7b6447c_1001
>   - mkl_random==1.1.1=py37h0573a6f_0
>   - libgfortran-ng==7.3.0=hdf63c60_0
>   - libgcc-ng==9.1.0=hdf63c60_0
>   - tk==8.6.10=hbc83047_0
>   - hdf5==1.10.4=hb1b8bf9_0
>   - h5py==2.10.0=py37h7918eee_0
>   - grpcio==1.27.2=py37hf8bcb03_0
>   - openssl==1.1.1g=h7b6447c_0
>   - libffi==3.3=he6710b0_1
>   - cudnn==7.6.5=cuda10.0_0
>   - protobuf==3.12.3=py37he6710b0_0

What OS was this environment originally installed on and exported from?
I'm running on MacOS Mojave Version 10.14.6
Any assistance would be great!

Thanks

**Comment by themasterlink** [comment]
Hey, 

the problem is that this uses `tensorflow==1.15.0=gpu_py37h0f0df58_0`

On MacOS there is no support for gpu. We have used Ubuntu 20.04 for this.

**Comment by lindenmp** [comment]
Hi,

I'm using an Ubuntu machine now (18.04.5 LTS) but am having trouble installing `cyglfw3==3.1.0.2`
Everything else in the environment installs just fine. Is this package essential?

FYI, I'm getting the following gcc error when installing `cyglfw3==3.1.0.2`

>   ERROR: Command errored out with exit status 1:
>    command: /home/lindenmp/anaconda3/envs/SingleViewReconstruction/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sja1fad2/cyglfw3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sja1fad2/cyglfw3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-02istk3j
>        cwd: /tmp/pip-install-sja1fad2/cyglfw3/
>   Complete output (23 lines):
>   Warning: 'classifiers' should be a list, got type 'tuple'
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-x86_64-3.7
>   creating build/lib.linux-x86_64-3.7/cyglfw3
>   copying cyglfw3/compatible.py -> build/lib.linux-x86_64-3.7/cyglfw3
>   copying cyglfw3/__init__.py -> build/lib.linux-x86_64-3.7/cyglfw3
>   copying cyglfw3/version.py -> build/lib.linux-x86_64-3.7/cyglfw3
>   copying cyglfw3/glfw3.pyx -> build/lib.linux-x86_64-3.7/cyglfw3
>   copying cyglfw3/cglfw3.pxd -> build/lib.linux-x86_64-3.7/cyglfw3
>   copying cyglfw3/glfw3.c -> build/lib.linux-x86_64-3.7/cyglfw3
>   running build_ext
>   building 'cyglfw3.glfw3' extension
>   creating build/temp.linux-x86_64-3.7
>   creating build/temp.linux-x86_64-3.7/cyglfw3
>   gcc -pthread -B /home/lindenmp/anaconda3/envs/SingleViewReconstruction/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lindenmp/anaconda3/envs/SingleViewReconstruction/include/python3.7m -c cyglfw3/glfw3.c -o build/temp.linux-x86_64-3.7/cyglfw3/glfw3.o -I/usr/local/include -I/opt/local/include -I/opt/local/lib
>   cyglfw3/glfw3.c:632:10: fatal error: GLFW/glfw3.h: No such file or directory
>    #include "GLFW/glfw3.h"
>             ^~~~~~~~~~~~~~
>   compilation terminated.
>   error: command 'gcc' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for cyglfw3

Which is odd, because I don't have troubles using gcc otherwise.

Thanks
