### ISSUE TITLE
Volume and Surface area estimation

### ISSUE THREAD

**Issue by srivathsan-g** [DLR-RM/SingleViewReconstruction#8]
Hi,
I have a problem where I need to estimate the volume and surface area of multiple similar (curved) objects from 2D image. Is it possible to do this using the trained model given in your repo? If yes, do point me in the right direction. Also, will I be required to use multiple views of the same objects for my problem? (It is possible for me to obtain multiple views for my use case)

Thanks in advance.

**Comment by themasterlink** [comment]
Hey,

sorry for the late response. 

> Is it possible to do this using the trained model given in your repo?

Yes, it would be possible. You can use the `UNetModel` to generate some normals, which you can then use in combination with the color images you have on your objects. But be aware that this was trained on indoor scenes, and if your objects are outside of that distribution, the predictions will be off. 

But you can tackle that by creating your own dataset, with BlenderProc for example. If you need help on that open an issue in that I am a maintainer there as well. Of course you would need some realistic outputs, which you could create with the SDFGen also provided in this project.

So there are many ways of solving this. 

> Also, will I be required to use multiple views of the same objects for my problem?

That shouldn't be a problem, however, my approach only uses one view, so giving it more information doesn't help the end result.

Best,
Max
