### ISSUE TITLE
I get an error in run_on_example_scenes_from_scenenet.py.

### ISSUE THREAD

**Issue by yujimori1967github** [DLR-RM/SingleViewReconstruction#9]
If you execute the following, an error will occur.
python run_on_example_scenes_from_scenenet.py

This script will perform a lot of steps automatically, including the download of SceneNet, BlenderProc, weights of the models used in this repo, and Blender.
If you agree with the download of the dataset and the open source code BlenderProc, type in yes:yes
download BlenderProc
download the full dataset SceneNet with corresponding textures
Download the scenenet textures
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=0B_CLZMBI0zcuQ3ZMVnp1RUkyOFk 

tar (child): /content/SingleViewReconstruction/BlenderProc/BlenderProc/resources/scenenet/SceneNetData/../texture_folder.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "run_on_example_scenes_from_scenenet.py", line 217, in <module>
    scenenet_data_folder = download_SceneNet(blender_proc_git_path)
  File "run_on_example_scenes_from_scenenet.py", line 66, in download_SceneNet
    os.remove(output)
FileNotFoundError: [Errno 2] No such file or directory: '/content/SingleViewReconstruction/BlenderProc/BlenderProc/resources/scenenet/SceneNetData/../texture_folder.tgz'

**Comment by themasterlink** [comment]
Hey,

the file stills seems to be accessible, can you run it again?

https://drive.google.com/uc?id=0B_CLZMBI0zcuQ3ZMVnp1RUkyOFk 

Best,
Max

**Comment by yujimori1967github** [comment]
Thank you for answering

I have tried the following in a google colab environment.
```
----
import gdown

url_for_texture_zip = "https://drive.google.com/uc?id=0B_CLZMBI0zcuQ3ZMVnp1RUkyOFk"
gdown.download(url_for_texture_zip, ".", quiet=False)
-----


As a result, I got the following error message.
-----
Permission denied: https://drive.google.com/uc?id=0B_CLZMBI0zcuQ3ZMVnp1RUkyOFk
Maybe you need to change permission over 'Anyone with the link'?
-----
```

Is it inaccessible to general users?

Thank you for your help

**Comment by themasterlink** [comment]
Hey,

I am sorry my first response was wrong, you are right the owner of the scenenet texture dataset changed the access rights :(

I will fix this in a few minutes, just let me make sure that I have a proper fix.

Best,
Max

**Comment by themasterlink** [comment]
Hey,

thank you so much for catching this bug I made a fix. There is sadly no better solution than to ask you to download the file yourself.

But, this at least works, I just have tried it :)

Best,
Max

**Comment by themasterlink** [comment]
Hey,

I fixed another path issue, if it works now, you can close this issue :) 

Best,
Max

**Comment by yujimori1967github** [comment]
###########################
You have to download the scenenet texture yourself: https://drive.google.com/uc?id=0B_CLZMBI0zcuQ3ZMVnp1RUkyOFk
The reason being that the owner changed the access permissions, we are sorry about that.
###########################
I understand. We apologize for the inconvenience.

**Comment by themasterlink** [comment]
Oh don't apologize, the script was broken, that is not your fault :)
